### PR TITLE
issue fixed #774 (adding import file option in sketch page)

### LINKED ISSUE #774: Add Feature to Load Images from Local System on Sketch Page (similar to any photo editor)
##  Requirements :

- Do not mess up any other part of the app that you are not working with
- Add a small button in the Editor Menu (Perhaps on the horizontal one)
- The functionality is self-explained by the title of the issue
- Write checks for importing images with extensions: .webp, .png, .jpeg. jpeg only

### PR DESCRIPTION
**Pull request by anshika208**
resolved #774
An import file option has been added in the sketch page on the horizontal bar. Only file type of jpeg/jpg/png/webp can be imported . for invalid file format an alert box will open .
docpen1
docpen2
docpen3
docpen4

### CODE REVIEW

File: src/pages/Sketch/components/Canvas.jsx [hunk 1]
```diff
@@ -493,27 +498,45 @@ function Canvas() {
...
+  const initiateload = () => document.getElementById("file-selector").click();
+  const loadimport= e =>{   
     let file = e.target.files[0];
-    if (!file) return;
-    let reader = new FileReader();
+    var textFile = /image.*/;
+
+
+    if (!(file.type.match(textFile))) { 
+     alert("Sorry, We cannot import the selected file . File should be of type jpg/jpeg/png/webp");
```
Comment (smaranjitghose) [inline src/pages/Sketch/components/Canvas.jsx:511]: Make this.

`OOPs! You didn't select an image. We only support jpg,png and webp'

Comment (anshika208) [reply src/pages/Sketch/components/Canvas.jsx:511]: ohk

File: src/pages/Sketch/components/Canvas.jsx [hunk 2]
```diff
@@ -3,13 +3,16 @@ import styles from "./canvas.module.scss";
...
 import { VscSaveAs } from "react-icons/vsc";
+import { BsBoxArrowInDown } from "react-icons/bs";
 import { RiDeleteBinLine } from "react-icons/ri";
 import { AiOutlineFolderOpen } from "react-icons/ai";
 import IconsLibrary from "./IconLibrary/IconsLibrary";
 import ReactSnackBar from "react-js-snackbar";
 import checkBox from "./../../../assets/images/checkmark.svg";
 import rough from "roughjs/bin/rough";
 
+
```
Comment (smaranjitghose) [inline src/pages/Sketch/components/Canvas.jsx:14]: Avoid these extra spaces as it might lead to merge conflicts in someone else's PR

**Review by smaranjitghose — APPROVED** [review]

File: src/pages/Sketch/components/Canvas.jsx (hunk 2 above)
Comment (anshika208) [reply src/pages/Sketch/components/Canvas.jsx:14]: sure! i will keep this in mind. thanku

**Comment by smaranjitghose** [comment]
Nice work @anshika208

File: src/pages/Sketch/components/Canvas.jsx [hunk 3]
```diff
@@ -449,7 +452,7 @@ function Canvas() {
         types: [
           {
             description: "Doc2pen Sketch Save File",
-            accept: { "application/d2ps": [".d2ps"] },
+            accept: { "image/*": [".jpg .jpeg .png"] },
```
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:455]: @anshika208 Why did you delete these lines. You are breaking an existing feature

Moreover, this function is to "Save" file. It's not for "loading" file. You edited the wrong function.

File: src/pages/Sketch/components/Canvas.jsx [hunk 4]
```diff
@@ -493,27 +498,45 @@ function Canvas() {
...
     );
     reader.readAsDataURL(file);
-  };
+    
+  }; 
+};
+
+    
+    
+
```
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:539]: adding lots of lines unnecessarily.

File: src/pages/Sketch/components/Canvas.jsx [hunk 5]
```diff
@@ -461,14 +464,16 @@ function Canvas() {
       accepts: [
         {
           description: "Doc2pen Sketch Save File",
-          extensions: ["d2ps"],
-          mimeTypes: ["application/d2ps"],
+          extensions: [".png"],
+          mimeTypes: ["image/*"],
```
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:468]: This one too

File: src/pages/Sketch/components/Canvas.jsx (hunk 3 above)
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:455]: @anshika208  Please dont delete important lines of code. 
'This is a braking change

Now d2ps files are saved with wrong mimeTypes and extensions

File: src/pages/Sketch/components/Canvas.jsx (hunk 5 above)
Comment (ashuvssut) [reply src/pages/Sketch/components/Canvas.jsx:468]: Moreover, `getNewFileHandle` is meant to **SAVE** d2ps file. It is not meant to **LOAD** image files.

So a completely irrelevant function is edited. The changes in this function are Obsolete

File: src/pages/Sketch/components/Canvas.jsx (hunk 4 above)
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:539]: Lines of code doesnt matter. Your contribution is what matters the most

File: src/pages/Sketch/components/Canvas.jsx (hunk 5 above)
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:468]: `getNewFileHandle` funciton is edited. This function is meant to **"SAVE"**  d2ps files. It is not meant to **LOAD** or **IMPORT** image files.

Thus, completely obsolete code is added here blindly.

Because of this change, d2ps files are not save with correct mimeType

File: src/pages/Sketch/components/Canvas.jsx (hunk 4 above)
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:539]: unformatted codes everywhere

File: src/pages/Sketch/components/Canvas.jsx (hunk 3 above)
Comment (anshika208) [reply src/pages/Sketch/components/Canvas.jsx:455]: I have changed the file format only because for opening d2ps files in our local system we need to have a definite kind of application and since the final setch was being saved in the png format that is the reason i changed the file format here

File: src/pages/Sketch/components/Canvas.jsx (hunk 5 above)
Comment (anshika208) [reply src/pages/Sketch/components/Canvas.jsx:468]: i know buddy!! but for making it more suitable i changed the file format for saving the progress so that we can view it easily.

File: src/pages/Sketch/components/Canvas.jsx (hunk 4 above)
Comment (anshika208) [reply src/pages/Sketch/components/Canvas.jsx:539]: @ashuvssut since i m new to contribution , there aremistakes from my side in and the mentor has already pin pointed it before to which i have replied too. i will keep this in mind from next time , i have already told the mentor this thing. And i don't think u can just label it as a bad contribution since only the file format has been changed that too for making it more easy , its not that any feature isnt working

File: src/pages/Sketch/components/Canvas.jsx (hunk 5 above)
Comment (ashuvssut) [reply src/pages/Sketch/components/Canvas.jsx:468]: > but for making it more suitable i changed the file format for saving the progress 

progress is saved in a special file format ".d2ps". this format is not an image. Its a raw buffer. not an image
Lets not argue upon this. Nobody is putting blame.
I reviewed this code in this PR in order to point out the flaws only.

**Comment by ashuvssut** [comment]
# here the gif that shows that d2ps loading feature was broken by your changes
It also shows that you have overwritten the d2ps loading code to convert it to your image loading code
Animation



This is the error that comes up (when d2ps file loading fails)
image

File: src/pages/Sketch/components/Canvas.jsx (hunk 4 above)
Comment (ashuvssut) [reply src/pages/Sketch/components/Canvas.jsx:539]: >  its not that any feature isnt working

se my comment below. the gif clearly shows that your deleted existing good code and replaced with you code blindly

File: src/pages/Sketch/components/Canvas.jsx [hunk 6]
```diff
@@ -493,27 +498,45 @@ function Canvas() {
       });
   };
 
-  const initiateLoadSaved = () => document.getElementById("file-selector").click();
-  const loadLastState = e => {
+
+  
+ 
+  const initiateload = () => document.getElementById("file-selector").click();
+  const loadimport= e =>{
```
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:505]: **You renamed the d2ps loading function to make your own image loading funciton**

File: src/pages/Sketch/components/Canvas.jsx [hunk 7]
```diff
@@ -493,27 +498,45 @@ function Canvas() {
...
+
+
+    if (!(file.type.match(textFile))) { 
+     alert("OOPs! You didn't select an image. We only support jpg,png and webp");
+        file.value = '';
+        return false;
+            }
+            else
+            {
+    let reader =  new FileReader();
```
Comment (ashuvssut) [inline src/pages/Sketch/components/Canvas.jsx:517]: d2ps is loaded as an image

d2ps is not an image
Its a raw buffer

code is modified blindly and thus d2ps feature broke


your should have CREATED YOUR OWN FUNCTION instead of MODIFYING THE CURRENT FUNCTION BLINDLY
