### PR TITLE
Fixed Image to PDF conversion, Resolution and Dimensions preserved

### LINKED ISSUE #1004: Bug: Wrong Size of Images Converted to PDF on Media Manip page
## Problem:
When image/s are converted to pdf, they are either stretched  / compressed in some direction, or cutoff at the page's edge

## Solution:
Each page of the pdf should be the same size as the original image to preserve its dimensions and resolution

I'll make a PR fixing this!

### PR DESCRIPTION
**Pull request by N-Shar-ma**
## Fixes #1004 

The output has now the exact same resolution, dimensions and quality as the original image!

## Changes Made:
- Made each page of the pdf the exact same size as the image on it, so there is no wastage of space as well as no loss of quality
- Named the file `converted.pdf`

### CODE REVIEW

File: src/pages/MediaManip/MediaManip.jsx [hunk 1]
```diff
@@ -99,24 +101,24 @@ export default function MediaManip() {
...
   };
 
-  const downloadPdf = async images => {
-    const doc = new jsPDF("p", "pt", "a4");
-    const width = doc.internal.pageSize.width;
-    const height = doc.internal.pageSize.height;
+  const downloadPdf = images => {
+    const doc = new jsPDF("l", "px", [images[0].width, images[0].height]);
+    doc.deletePage(1);
+    // const pageWidth = doc.internal.pageSize.width;
```
Comment (smaranjitghose) [inline src/pages/MediaManip/MediaManip.jsx:107]: Remove the commented lines please

**Review by smaranjitghose — APPROVED** [review]

**Comment by N-Shar-ma** [comment]
@smaranjitghose Done!

**Comment by N-Shar-ma** [comment]
It works perfectly locally, any suggestions on how to make it pass the failing checks?
